Upgrade ANF SDK version
Azure-Samples/netappfiles-dotnetcore-dual-protocol-sdk-sample pull request #2
Opened 2021-09-07 20:20 UTC by AdelGhabboun

1. Upgraded ANF SDK version to 1.13.0
2. Upgraded .NET version to .NET 5.0
3. Added logic to read password from Console.

2021-09-08 11:26 UTC, hildurhodd approved these changes
LGTM

2021-09-15 18:25 UTC, paulomarquesc commented on src/anf-dotnetcore-dual-protocol-sdk-sample/Program.cs
> +            if (string.IsNullOrWhiteSpace(DomainJoinUserPassword))
>DomainJoinUserPassword [](http://example.com/codeflow?start=42&length=22)

Camel Case

2021-09-15 18:25 UTC, paulomarquesc commented on src/anf-dotnetcore-dual-protocol-sdk-sample/Program.cs
> +                DomainJoinUserPassword,
>DomainJoinUserPassword [](http://example.com/codeflow?start=16&length=22)

Camel Case

2021-09-15 18:38 UTC, paulomarquesc requested changes
:clock1:

2021-09-15 18:38 UTC, paulomarquesc commented on src/anf-dotnetcore-dual-protocol-sdk-sample/Program.cs
> +            string DomainJoinUserPassword = Utils.GetConsolePassword();
>DomainJoinUserPassword [](http://example.com/codeflow?start=19&length=22)

Camel Case

2021-09-15 20:55 UTC, paulomarquesc approved these changes
:shipit:

2021-09-15 21:05 UTC, merged